### ISSUE TITLE
Allow for invalid URLs (possible in custom `fetch`)

### ISSUE THREAD

**Issue by cuibonobo** [haverstack/axios-fetch-adapter#11]
I've got a new problem : it returns `ERR_INVALID_URL` when using an `url` that starts with `/`, which, using normal `fetch`, would indeed be incorrect, but using a custom one in an SSR context, is proper.

Thanks

_Originally posted by @KaKi87 in https://github.com/haverstack/axios-fetch-adapter/issues/6#issuecomment-1676491299_

**Comment by cuibonobo** [comment]
Fixed in #12.

**Comment by KaKi87** [comment]
Thanks, unfortunately, I'm now experiencing the following error :
```
ReferenceError: fetchAdapter is not defined
    at /node_modules/@haverstack/axios-fetch-adapter/lib/index.d.ts:10:16
```
Thanks

**Comment by cuibonobo** [comment]
I reverted a change that may have been causing this. Version 0.12.0 was tested against an application where this library is used and the tests are now passing.

**Comment by KaKi87** [comment]
Thanks, one last thing though ;
The following doesn't work :
```js
import { createFetchAdapter } from '@haverstack/axios-fetch-adapter';
```
Only the following does :
```js
import axiosFetchAdapter from '@haverstack/axios-fetch-adapter';
const { createFetchAdapter } = axiosFetchAdapter;
```
Thanks
