### ISSUE TITLE
SyntaxError: Named export 'createFetchAdapter' not found

### ISSUE THREAD

**Issue by sarhugo** [haverstack/axios-fetch-adapter#8]
Trying to import the createFetchAdapter from the lib

`import { createFetchAdapter } from "@haverstack/axios-fetch-adapter"`

but I get the error:

```
SyntaxError: Named export 'createFetchAdapter' not found. The requested module '@haverstack/axios-fetch-adapter' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@haverstack/axios-fetch-adapter/lib/index.esm.js';
const { createFetchAdapter } = pkg;
```

Also tried the suggested solution but it doesn't work because it seems to import just the default export which is the regular fetchAdapter

**Comment by sarhugo** [comment]
Nevermind, it seems that the issue is related to vite when using CJS imports with default and named exports. I found this plugin that solves the issue https://github.com/cyco130/vite-plugin-cjs-interop.
I leave this open in case you see anything that can be done in order to prevent it

**Comment by cuibonobo** [comment]
I appreciate you reporting this. I've been pretty busy this month but I will look into this issue and see if there's something to be done about it.

**Comment by cuibonobo** [comment]
Used [`publint`](https://publint.dev) to get suggestions for CJS and ESM export compatibility. I'm not sure if this will fix the specific issue with Vite, but I went ahead and closed this.
